# Default values for roar-db-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: mysql
replicaCount: 1
image:
 prod:
   repository: bclaster/roar-db-image
   tag: v1
 test:
   repository: bclaster/roar-db-test
   tag: v4
deployment:
  ports:
    name: mysql
    containerPort: 3306
  env:
    MYSQL_DATABASE: "registry"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root+1"
    MYSQL_USER: "admin"
service:
  frontendPortName: "mysql"
  externalPort: 3306
  internalPort: 3306
roar-db:
  stage: PROD

