apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: roar-web
  name: roar-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: roar-web
    spec:
      containers:
      - image: bclaster/roar-web-image:v1
        imagePullPolicy: Always
        name: roar-web
        ports:
        - containerPort: 8080
          name: web
